version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest-windowsservercore"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    container_name: "efserver"
    hostname: "efserver"
    tty: true
  websphere:
    image: "electricflow/websphere85s:latest-win"
    ports:
      - "9060:9060"
      - "9043:9043"
      - "9443:9443"
      - "7808:7800"
      - "8080:80"
    container_name: websphere85s
    hostname: "websphere85s"
    tty: true
    environment:
    - EF_SERVER_HOST=efserver
    - EF_SERVER_ADMIN_USER=admin
    - EF_SERVER_ADMIN_PASS=changeme
    - EF_RESOURCE_NAME="websphere85s"
    - WAS_CELL_NAME=websphere85sCell01
    - WAS_NODE_NAME=websphere85sNode01
    restart: always
networks:
  default:
    external:
      name: nat
