@files = (
    ['//property[propertyName="Util.pm"]/value', 'WebSphere/Util.pm'],
	['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="WebSphereCreateConfigForm"]/value'  , 'WebSphereCreateConfigForm.xml'],
	['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="WebSphereEditConfigForm"]/value'  , 'WebSphereEditConfigForm.xml'],
	
	['//property[propertyName="stopserver_matchers"]/value', 'matchers/stopServerMatchers.pl'],
	['//property[propertyName="startserver_matchers"]/value', 'matchers/startServerMatchers.pl'],
	['//property[propertyName="wsadmin_matchers"]/value', 'matchers/wsadminMatchers.pl'],
	['//property[propertyName="checkserver_matchers"]/value', 'matchers/checkServerMatchers.pl'],
	['//property[propertyName="checkpage_matchers"]/value', 'matchers/checkPageMatchers.pl'],
	['//property[propertyName="checkapp_matchers"]/value', 'matchers/checkAppMatchers.pl'],
	['//property[propertyName="datasource_matchers"]/value', 'matchers/datasourceMatchers.pl'],
	['//property[propertyName="jdbcprovider_matchers"]/value', 'matchers/jdbcProviderMatchers.pl'],
	
	['//procedure[procedureName="StartServer"]/step[stepName="StartInstance"]/command' , 'server/startServer.pl'],
	['//procedure[procedureName="StopServer"]/step[stepName="StopInstance"]/command' , 'server/stopServer.pl'],
	['//procedure[procedureName="CheckServerStatus"]/step[stepName="CheckServerStatus"]/command' , 'server/checkServerStatus.pl'],
	['//procedure[procedureName="CheckPageStatus"]/step[stepName="CheckPageStatus"]/command' , 'server/checkPageStatus.pl'], 
	['//procedure[procedureName="RunCustomJob"]/step[stepName="RunJob"]/command' , 'server/runCustomJob.pl'],
	['//procedure[procedureName="CheckApp"]/step[stepName="CheckApp"]/command' , 'server/checkApp.pl'],
	['//procedure[procedureName="StartApp"]/step[stepName="StartApp"]/command' , 'server/startApp.pl'],
	['//procedure[procedureName="StopApp"]/step[stepName="StopApp"]/command' , 'server/stopApp.pl'],
	['//procedure[procedureName="DeployApp"]/step[stepName="DeployApp"]/command' , 'server/deployApp.pl'],
	['//procedure[procedureName="UndeployApp"]/step[stepName="UndeployApp"]/command' , 'server/undeployApp.pl'], 
	['//procedure[procedureName="CreateDatasource"]/step[stepName="CreateDatasource"]/command' , 'server/createDatasource.pl'], 
	['//procedure[procedureName="DeleteDatasource"]/step[stepName="DeleteDatasource"]/command' , 'server/deleteDatasource.pl'], 
	['//procedure[procedureName="CreateJDBCProvider"]/step[stepName="CreateJDBCProvider"]/command' , 'server/createJDBCProvider.pl'], 
	['//procedure[procedureName="DeleteJDBCProvider"]/step[stepName="DeleteJDBCProvider"]/command' , 'server/deleteJDBCProvider.pl'], 
	['//procedure[procedureName="PublishWSDL"]/step[stepName="PublishWSDL"]/command' , 'server/publishWSDL.pl'],

	['//procedure[procedureName="CreateConfiguration"]/step[stepName="CreateConfiguration"]/command' , 'conf/createcfg.pl'],
	['//procedure[procedureName="CreateConfiguration"]/step[stepName="CreateAndAttachCredential"]/command' , 'conf/createAndAttachCredential.pl'],
	['//procedure[procedureName="DeleteConfiguration"]/step[stepName="DeleteConfiguration"]/command' , 'conf/deletecfg.pl'], 
	
	['//property[propertyName="ec_setup"]/value', 'ec_setup.pl'], 
 
	['//procedure[procedureName="CreateDatasource"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-CreateDatasource.xml'],
	['//procedure[procedureName="DeleteDatasource"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-DeleteDatasource.xml'], 
	['//procedure[procedureName="CreateJDBCProvider"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-CreateJDBCProvider.xml'],
	['//procedure[procedureName="DeleteJDBCProvider"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-DeleteJDBCProvider.xml'], 
	['//procedure[procedureName="StartServer"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-StartServer.xml'],
	['//procedure[procedureName="StopServer"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-StopServer.xml'],
	['//procedure[procedureName="CheckServerStatus"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-CheckServerStatus.xml'],
	['//procedure[procedureName="CheckPageStatus"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-CheckPageStatus.xml'],
	['//procedure[procedureName="RunCustomJob"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-RunCustomJob.xml'],
	['//procedure[procedureName="CheckApp"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-CheckApp.xml'],
	['//procedure[procedureName="StartApp"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-StartApp.xml'],
	['//procedure[procedureName="StopApp"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-StopApp.xml'],
	['//procedure[procedureName="DeployApp"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-DeployApp.xml'],
	['//procedure[procedureName="PublishWSDL"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'parameterForms/ec_parameterForm-PublishWSDL.xml'],
);
